// <auto-generated />
using ARMSYSTEM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ARMSYSTEM.Migrations
{
    [DbContext(typeof(PhonesContext))]
    [Migration("20171012114151_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ARMSYSTEM.Models.BlackList", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descripton");

                    b.Property<long>("phone");

                    b.HasKey("id");

                    b.HasIndex("phone")
                        .IsUnique();

                    b.ToTable("BlackList");
                });

            modelBuilder.Entity("ARMSYSTEM.Models.Phones", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apartment");

                    b.Property<string>("City");

                    b.Property<string>("DateUpdate");

                    b.Property<string>("Family");

                    b.Property<string>("House");

                    b.Property<string>("Name");

                    b.Property<string>("Patronymic");

                    b.Property<long>("Phone");

                    b.Property<string>("Sex");

                    b.Property<string>("Street");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
